#!/bin/bash

mkdir 'program'
mkdir 'program/b/fact()'
mkdir 'program/b/fact()/a'
mkdir 'program/b/fact()/a/5'
mkdir 'program/:fact_n'
mkdir 'program/:fact_n/ifelse()'
mkdir 'program/:fact_n/ifelse()/a'
mkdir 'program/:fact_n/ifelse()/a/<='
mkdir 'program/:fact_n/ifelse()/a/<=/a'
mkdir 'program/:fact_n/ifelse()/a/<=/a/n'
mkdir 'program/:fact_n/ifelse()/a/<=/b'
mkdir 'program/:fact_n/ifelse()/a/<=/b/1'
mkdir 'program/:fact_n/ifelse()/b'
mkdir 'program/:fact_n/ifelse()/b/1'
mkdir 'program/:fact_n/ifelse()/c'
mkdir 'program/:fact_n/ifelse()/c/*'
mkdir 'program/:fact_n/ifelse()/c/*/a'
mkdir 'program/:fact_n/ifelse()/c/*/a/n'
mkdir 'program/:fact_n/ifelse()/c/*/b'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a/-'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a/-/a'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a/-/a/n'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a/-/b'
mkdir 'program/:fact_n/ifelse()/c/*/b/fact()/a/-/b/1'
