#!/bin/bash

#Mergesort
mkdir -p 'program/:msort_l/ifelse()/a/>/a/count()/a/l'
mkdir -p 'program/:msort_l/ifelse()/a/>/b/1'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/a/msort()/a/part()/a/l'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/a/msort()/a/part()/b/0'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/a/msort()/a/part()/c/\\/a/count()/a/l'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/a/msort()/a/part()/c/\\/b/2'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/b/msort()/a/part()/a/l'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/b/msort()/a/part()/b/\\/a/count()/a/l'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/b/msort()/a/part()/b/\\/b/2'
mkdir -p 'program/:msort_l/ifelse()/b/merge()/b/msort()/a/part()/c/count()/a/l'
mkdir -p 'program/:msort_l/ifelse()/c/l'

#Merge
mkdir -p 'program/:merge_l_ll/ifelse()/a/|/a/==/a/count()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/a/|/a/==/b/0'
mkdir -p 'program/:merge_l_ll/ifelse()/a/|/b/==/a/count()/a/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/a/|/b/==/b/0'
mkdir -p 'program/:merge_l_ll/ifelse()/b/join()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/b/join()/b/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/a/<=/a/first()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/a/<=/b/first()/a/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/b/join()/a/@/a/first()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/b/join()/b/merge()/a/part()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/b/join()/b/merge()/a/part()/b/1'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/b/join()/b/merge()/a/part()/c/count()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/b/join()/b/merge()/b/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/c/join()/a/@/a/first()/a/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/c/join()/b/merge()/a/l'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/c/join()/b/merge()/b/part()/a/ll'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/c/join()/b/merge()/b/part()/b/1'
mkdir -p 'program/:merge_l_ll/ifelse()/c/ifelse()/c/join()/b/merge()/b/part()/c/count()/a/ll'
